Request to add ysksuzuki as sig-lb reviewer
cilium/community pull request #36
Opened 2023-06-09 12:36 UTC by ysksuzuki

I'd like to request you to add me as sig-lb reviewer. I have reviewed the following PRs related to the LB area.

add native tunnel encapsulation support for the XDP Loadbalancer
https://github.com/cilium/cilium/pull/24422

datapath: support Hybrid-DSR mode for Geneve dispatch
https://github.com/cilium/cilium/pull/25553

Also, I contributed to adding new LB feature.

Support DSR with Geneve dispatch
https://github.com/cilium/cilium/pull/23890

2023-06-09 20:36 UTC, joestringer approved these changes

2023-06-13 06:25 UTC, xmulligan approved these changes

2023-06-14 16:46 UTC, joestringer requested changes
Actually, looking back I think you're welcome to join @cilium/sig-lb, but this file should include all members from the file:

https://github.com/orgs/cilium/teams/sig-lb

2023-06-15 05:03 UTC, ysksuzuki commented
@joestringer Thank you for the review!

> Actually, looking back I think you're welcome to join https://github.com/orgs/cilium/teams/sig-lb, but this file should include all members from the file

I have added all members of sig-lb to the file. Please take a look.

2023-06-15 22:43 UTC, joestringer approved these changes

2023-06-15 22:43 UTC, merged